vslam:
    camera:
      ros__parameters:
        device_type: ''
        serial_no: ''
        usb_port_id: ''

        infra_height: 480
        infra_width: 640
        infra_qos: "SENSOR_DATA"

        enable_color: false
        enable_depth: true
        enable_infra1: true
        enable_infra2: false

        enable_pointcloud: false
        filters: ''


        pointcloud_texture_index: 0
        pointcloud_texture_stream: RS2_STREAM_COLOR

        stereo_module:
          emitter_enabled: true
        unite_imu_method: ''

        rosbag_filename: ''
